repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        files: \.ya?ml$
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-symlinks
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff
        name: ruff-sort-imports
        args: ["--select", "I", "--fix"]
      - id: ruff-format
      - id: ruff
        name: ruff-linting
        args:
          - --extend-select
          - C,W,E,F,B,A,PT,RET,SIM,PD,ERA,PLC,PLE,PLW,NPY,PERF,RUF
          - --line-length
          - "100"

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        description: Runs hadolint to lint Dockerfiles
        language: system
        types: [ "dockerfile" ]
        entry: hadolint
        args:
          - --style
          - DL3015

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
