name: "Test GitHub Action"
run-name: test-github-action
env:
  SBOM_FILE: "./tests/files/sbom_secObserve.cdx.json"
on:
  workflow_dispatch:
  push:
    branches:
      - "feat/github-action-release"

jobs:
  analyze-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run Evaluation Action
        uses: ./
        id: analyze-sbom
        with:
          SBOM_PATH: ${{ env.SBOM_FILE }}
          BREAK_ENABLED: false
      - name: Upload SBOM evaluation artifact
        uses: actions/upload-artifact@v4
        with:
          name: evaluated_sbom
          path: ${{ github.workspace }}/sbom/evaluated_sbom.csv
          if-no-files-found: error
