
name: "Pull Request: pre-commit"

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5

    - name: install hadolint
      run: |
        sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
        sudo chmod +x /bin/hadolint

    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: "--show-diff-on-failure --color=always --from-ref origin/main --to-ref HEAD"
