name: Test published GitHub Action
run-name: test
env:
  SBOM_PATH: "./tests/files/sbom_secObserve.cdx.json"
on:
  push:
    branches: [ feat/github-action-release ]

jobs:
  required:
    runs-on: ubuntu-latest
    steps:
      - name: approval information
        run: echo "Please publish the GitHub Action to the GitHub Marketplace before continuing"

  tests:
    runs-on: ubuntu-latest
    environment: 'publish-action-to-github-marketplace'
    needs: required
    steps:
      - name: get action tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          semver_only: true

      - name: check tag
        run: echo ${{ steps.release-label.outputs.level}}

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: MaibornWolff/purl-patrol@v1.0.1
        with:
          SBOM_PATH: ${{env.SBOM_PATH}}
