name: Publish Azure DevOps Extension

on:
  push:
    branches: [main]

jobs:
  run_and_publish_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/Jod'
      
      - name: Install TFX CLI
        run: npm install -g tfx-cli

      - name: Install dependencies
        run: npm install
        working-directory: ./extensions/azure-devops/task/PurlPatrolV1 

      - name: Test
        run: npm run test
        working-directory: ./extensions/azure-devops/task/PurlPatrolV1 
        
      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: './extensions/azure-devops/task/PurlPatrolV1/test-result.txt'
          if-no-files-found: 'error'

  package_extension_and_publish_build_artifacts:
    runs-on: ubuntu-latest
    needs: run_and_publish_tests
    env:
      RELEASE_VERSION: ${{ needs.semantic-release.outputs.RELEASE_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/Jod'
      - name: Install dependencies
        run: npm install
        working-directory: ./extensions/azure-devops/task/PurlPatrolV1 
      
      - name: Install TFX CLI
        run: npm install -g tfx-cli

      - name: Compile Javascript
        run: npm run build
        working-directory: ./extensions/azure-devops/task/PurlPatrolV1 

      - name: Create Azure DevOps Extension vsix
        working-directory: ./extensions/azure-devops
        run: |
          tfx extension create --root ./ --manifest-globs vss-extension.json \
          --override '{"version": "${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}"}' \
          --share-with PURL-patrol
  
      - name: Copy Files to Artifact Staging Directory
        run: cp ./extensions/azure-devops/*.vsix $GITHUB_WORKSPACE

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packaged-extension
          path: "${{ github.workspace }}/*.vsix"
          if-no-files-found: 'error'

  download_build_artifacts_and_publish_the_extension:
    runs-on: ubuntu-latest
    needs: package_extension_and_publish_build_artifacts
    env:
      PAT: ${{ secrets.AZURE_PAT }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/Jod'

      - name: Install TFX CLI
        run: npm install -g tfx-cli
      
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: packaged-extension

      - name: Publish Azure DevOps Extension
        run: |
          tfx extension publish --vsix ${{ github.workspace }}/*.vsix --token $PAT