name: Test published GitHub Action
run-name: test
env:
  SBOM_PATH: "./tests/files/sbom_secObserve.cdx.json"
  LICENSE_POLICY_PATH: "./tools/license_policy.json/mw_license_policy.json"
on:
  release:
    types:
      - published

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - uses: MaibornWolff/purl-patrol@v1.0.1
       with:
         SBOM_PATH: ${{env.SBOM_PATH}}
         LICENSE_POLICY_PATH: ${{env.LICENSE_POLICY_PATH}}
