name: Test published GitHub Action
run-name: test
env:
  SBOM_PATH: "./tests/files/sbom_secObserve.cdx.json"
  LICENSE_POLICY_PATH: "./tools/license_policy.json/mw_license_policy.json"
  APPROVAL_ARTIFACT_PATH: "./tests/files/approval_information.txt"
on:
  workflow_call:

jobs:
  required:
    runs-on: ubuntu-latest
    steps:
      - name: approval information
        run: echo "Please publish the GitHub Action to the GitHub Marketplace before continuing"

  tests:
    runs-on: ubuntu-latest
    environment: 'publish-action-to-github-marketplace'
    needs: required
    steps:

     - name: Checkout code
       uses: actions/checkout@v4

     - uses: MaibornWolff/purl-patrol@v1.0.1
       with:
         SBOM_PATH: ${{env.SBOM_PATH}}
         LICENSE_POLICY_PATH: ${{env.LICENSE_POLICY_PATH}}
