name: Test published GitHub Action
run-name: test
env:
  SBOM_PATH: "./tests/files/sbom_sec_observe.cdx.json"
on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.12"

      - name: Create venv and install pytest
        run: |
          python -m venv .venv
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
          python -m pip install --upgrade pip
          pip install pytest
          pip install tabulate

      - name: Unit tests license-policy-check
        run: cd tools/license-policy-check/testing && pytest test_check_usage_policy.py -q && cd ../../..

      - uses: MaibornWolff/purl-patrol@a1f87b1af3982be77050d4ac043937b5571bf36d # main
        with:
          SBOM_PATH: ${{env.SBOM_PATH}}
          BREAK_ENABLED: false
