name: Test published GitHub Action
run-name: test
env:
  SBOM_PATH: "./tests/files/sbom_secObserve.cdx.json"
on:
  push:
    branches: [ feat/github-action-release ]

jobs:
  required:
    runs-on: ubuntu-latest
    steps:
      - name: approval information
        run: echo "Please publish the GitHub Action to the GitHub Marketplace before continuing"

  tests:
    runs-on: ubuntu-latest
    environment: 'publish-action-to-github-marketplace'
    needs: required
    steps:
      - name: get action tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: maibornwolff/purl-patrol
          releases-only: true
        id: tag

      - name: check tag
        run: echo ${{ steps.tag.outputs.tag}}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION

      - uses: MaibornWolff/purl-patrol@v1.0.1
        with:
          SBOM_PATH: ${{env.SBOM_PATH}}
