name: Test published GitHub Action
run-name: test
env:
  SBOM_PATH: "./tests/files/sbom_sec_observe.cdx.json"
on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create venv and install pytest
        run: |
          python -m venv .venv
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
          python -m pip install --upgrade pip
          pip install pytest
          pip install tabulate

      - name: Unit tests license-policy-check
        run: cd tools/license-policy-check/testing && pytest test_check_usage_policy.py -q && cd ../../..

      - uses: MaibornWolff/purl-patrol@main
        with:
          SBOM_PATH: ${{env.SBOM_PATH}}
          BREAK_ENABLED: false
