name: Test published GitHub Action
run-name: test
env:
  SBOM_PATH: "./tests/files/sbom_sec_observe.cdx.json"
on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: MaibornWolff/purl-patrol@main
        with:
          SBOM_PATH: ${{env.SBOM_PATH}}
          BREAK_ENABLED: false
