name: Release PURL Patrol
run-name: release-purl-patrol
on:
  push:
    branches: [main]

jobs:
  # test:

  semantic-release:
    # needs: [test]
    runs-on: ubuntu-latest
    name: semantic-release
    outputs:
      RELEASE_TAG: ${{ steps.release.outputs.RELEASE_TAG }}
      RELEASE_VERSION: ${{ steps.release.outputs.RELEASE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm install
      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # automatically created by GH action
        run: npx semantic-release   # npx is included in npm -> Ubuntu


  delivery:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    name: Push to container registry
    needs: [semantic-release]
    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ needs.semantic-release.outputs.RELEASE_TAG }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/maibornwolff/purl-patrol:latest
            ghcr.io/maibornwolff/purl-patrol:${{ needs.semantic-release.outputs.RELEASE_VERSION }}

      - name: Create SBOM with Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
          docker scout sbom ghcr.io/maibornwolff/purl-patrol:${{ needs.semantic-release.outputs.RELEASE_VERSION }} --format cyclonedx -o sbom.cdx.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.cdx.json

  call-github-action:
    needs: delivery
    uses: ./.github/workflows/public_testing_github_actions.yaml

  calling-publish-azure-extension-workflow:
    needs: delivery
    uses: ./.github/workflows/publish-azure-extension.yml
    with:
      release_version: ${{needs.semantic-release.outputs.RELEASE_VERISON}}
