on:
  workflow_call:
    inputs:
      release_version:
        required: true

jobs:

  use-version:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ inputs.release_version }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Use release version
        run: echo ${{ env.RELEASE_VERSION }}
