on:
  workflow_call:
    inputs:
      release_version:
        required: true

jobs:

  use-version:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ inputs.release_version }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Use release version
        run: echo ${{ env.RELEASE_VERSION }}

      - name: update docker image tag
        run: sed -i -e 's/latest/${{ env.RELEASE_VERSION }}/' ./.github/workflows/test.ts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm install

      - name: test for ts
        run: |
          tsc ./.github/workflows/test.ts
          node ./.github/workflows/test.js
