name: testing sbom creation
on:
  push:
    branches:
      - feat/SBOM-creation

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/maibornwolff/purl-patrol:latest
            ghcr.io/maibornwolff/purl-patrol:1.6.0

      - uses: oras-project/setup-oras@v1

      - name: Create SBOM with Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
          docker scout sbom ghcr.io/maibornwolff/purl-patrol:1.6.0 --format cyclonedx -o sbom.cdx.json
          oras attach ghcr.io/maibornwolff/purl-patrol:1.6.0 sbom.cdx.json --artifact-type docker/sbom
