on:
  push:
    branches:
      - feat/azure-extension
env:
  RELEASE_VERSION = ${{ needs.call-workflow.outputs.workflow_output }}
jobs:
  call-workflow:
    name: call other workflow
    uses: ./.github/workflows/test.yml

  use-version:
    needs: call-workflow
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Use release version
        run: echo ${{ env.RELEASE_VERSION }}

      - name: update docker image tag
        run: sed -i -e 's/latest/${{ env.RELEASE_VERSION }}/' ./.github/workflows/test.ts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm install

      - name: test for ts
        run: |
          tsc ./.github/workflows/test.ts 
          node ./.github/workflows/test.js
