name: testing sbom creation
on:
  push:
    branches:
      - feat/SBOM-creation

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v4

      - name: Create SBOM with Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
          docker scout sbom ghcr.io/maibornwolff/purl-patrol:1.6.0 --format cyclonedx -o sbom.cdx.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.cdx.json
