on:
  push:
    branches:
      - feat/azure-extension
jobs:
  call-workflow:
   - uses: ./.github/workflows/test.yml

  use-version:
    needs: call-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Use release version
        run: echo ${{ needs.call-workflow.outputs.RELEASE_VERSION}}