name: testing call of azure pipeline
on:
  push:
    branches:
      - feat/azure-extension
jobs:
  test_the_published_extension:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure cli
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true

      - name: Get token from service principal to test published extension
        run: |
         TOKEN=$(az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 --query "accessToken" -o tsv)
         echo "ACCESS_TOKEN=${TOKEN}" >> $GITHUB_ENV

      - uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: 'https://dev.azure.com/PURL-patrol/purl-patrol'
          azure-pipeline-name: 'purl-patrol-pipeline-test/azure-pipelines.yml'
          azure-devops-token: '${{env.ACCESS_TOKEN}}'
